name: Build and deploy Node.js app to Azure Web App - todoHw2Kriz

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for OIDC login to Azure
      contents: read   # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Adjusted based on your previous logs indicating Node 22 used, 20.x is LTS
          cache: 'npm'

      - name: npm install
        run: npm ci # Using 'ci' for cleaner installs based on package-lock.json

      # If your app has a specific build command defined in package.json, uncomment the next two lines
      # - name: Build application (if needed)
      #   run: npm run build --if-present

      # If you have tests defined in package.json, uncomment the next two lines
      # - name: Run tests (if needed)
      #   run: npm test --if-present

      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A82892F131724703BBC775224E80CCBE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6D47BFA71FBD403582F752C2EBC0DDED }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7AE2256AADEE4D4395AF916AFCB36070 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp # Added id here to reference outputs.webapp-url
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'todoHw2Kriz' # Your App Service name
          package: . # Deploy the current directory (which includes node_modules after npm ci)
          # slot-name: 'Production' # This is the default, so it's optional unless you use other slots

      # Optional: Logout from Azure
      - name: Logout from Azure
        if: always()
        run: |
          az logout
          az cache purge
          az account clear