name: Build and deploy Node.js app to Azure Web App - todoHw2Kriz

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write 
      contents: read   

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' 
          cache: 'npm'

      - name: npm install
        run: npm ci 

      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A82892F131724703BBC775224E80CCBE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6D47BFA71FBD403582F752C2EBC0DDED }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7AE2256AADEE4D4395AF916AFCB36070 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp 
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'todoHw2Kriz' 
          package: . 

      - name: Logout from Azure
        if: always()
        run: |
          az logout
          az cache purge
          az account clear